spring:
  application:
    name: SpringBoot-Multi-Environment
  profiles:
    active: '@profileActive@'

server:
  port: 8081
  servlet:
    context-path: /api
    
# development configuration

---
spring:
  config:
    activate:
      on-profile:
      - development
  datasource:
    url: jdbc:h2:mem:hamburger
    username: postgres
    password: postgres

# staging configuration

---
spring:
  config:
    activate:
      on-profile: 
      - staging
  datasource:
    url: jdbc:mariadb://localhost:3306/hamburger
    username: postgres
    password: postgres

# production configuration

---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:postgresql://localhost:5432/hamburger
    username: postgres
    password: postgres      